### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by mrgreen3** [kaihendry/dotfiles#4]
Thought I was going mad (not that I already am giving what is happening). Watched the video saw the configs... sudo make install... nothing. In the end put your config side by side with mine and saw the '//' on mouse wheel lines. A duh! moment

All working now, thank you :-)

**Comment by zenikigai** [comment]
> Thought I was going mad (not that I already am giving what is happening). Watched the video saw the configs... sudo make install... nothing. In the end put your config side by side with mine and saw the '//' on mouse wheel lines. A duh! moment
> 
> All working now, thank you :-)

what do you mean by "side by side" btw?

**Comment by mrgreen3** [comment]
Side by side as in differences, such an old post I had forgotten all about it.
